[package]
name = "gramatika"
version = "0.1.0"
edition = "2018"
authors = ["Danny McGee <dannymcgee@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "../../README.md"
repository = "http://github.com/dannymcgee/gramatika"

[dependencies]
lazy_static = "1.4"
regex = "1.5"
gramatika-macro = { path = "../gramatika-macro", optional = true }

[features]
default = ["macros"]
macros = ["gramatika-macro"]
